<?php
	
$IN_FILE = "tempconv.txt";
$OUT_FILE = "tempconv.asm";

// Purpose: predicts jump labels
require "lib/common.php";
	
if (!file_exists($IN_FILE))
	die("Can't find {$IN_FILE}");

$asmfile = file($IN_FILE);
$h = fopen($OUT_FILE, 'w');

//$jumpmap = [];

for ($chnum = $i = 0; $i < count($asmfile); $i++) {
	$line = $asmfile[$i];
	
	if (strpos($line, "SndData_") === 0) {
		$localLbl = [];
		$defId = $callId = 0;
		outraw($line);
	} else if (strpos($line, "\tsndcall") === 0) {
		// This assumes the jumplists were generated by a tool that ordered the call order
		$p = strrpos($line, "\$"); // Last one! since sndloopcnt has two
		if ($p === false)
			die("strpos failed!");
		$addr = substr($line, $p + 1, 4);
		
		//$instruct = trim(explode(" ", $line, 2)[0]);
		//if ($instruct != "sndcall")
		
		// If don't already have that address, set it
		if (!isset($localLbl[$addr])) {
			$localLbl[$addr] = $callId;
			$callId++;
		}
		outraw(substr($line, 0, $p).".call{$localLbl[$addr]}\r\n");	
		
	} else if (strpos($line, "\tsndret") === 0 || strpos($line, "\tsndloop ") === 0) {
		outraw($line);
		// Prevent extra at the end
		if ($i+1<count($asmfile) && strpos($asmfile[$i+1], "Snd") !== 0) {
			outraw(".call{$defId}:\r\n");
			$defId++;
		}
	} else {
		outraw($line);
	}
}

fclose($h);

function outraw($txt) {
	global $h;
	fwrite($h, $txt); 
}